# Autogenerated wrapper script for HMMER_jll for i686-linux-musl
export alimask, esl_afetch, esl_alimanip, esl_alimap, esl_alimask, esl_alimerge, esl_alipid, esl_alistat, esl_compalign, esl_compstruct, esl_construct, esl_histplot, esl_mask, esl_reformat, esl_selectn, esl_seqrange, esl_seqstat, esl_sfetch, esl_shuffle, esl_ssdraw, esl_weight, hmmalign, hmmbuild, hmmconvert, hmmemit, hmmfetch, hmmlogo, hmmpgmd, hmmpress, hmmscan, hmmsearch, hmmsim, hmmstat, jackhmmer, makehmmerdb, nhmmer, nhmmscan, phmmer

using GSL_jll
JLLWrappers.@generate_wrapper_header("HMMER")
JLLWrappers.@declare_executable_product(alimask)
JLLWrappers.@declare_executable_product(esl_afetch)
JLLWrappers.@declare_executable_product(esl_alimanip)
JLLWrappers.@declare_executable_product(esl_alimap)
JLLWrappers.@declare_executable_product(esl_alimask)
JLLWrappers.@declare_executable_product(esl_alimerge)
JLLWrappers.@declare_executable_product(esl_alipid)
JLLWrappers.@declare_executable_product(esl_alistat)
JLLWrappers.@declare_executable_product(esl_compalign)
JLLWrappers.@declare_executable_product(esl_compstruct)
JLLWrappers.@declare_executable_product(esl_construct)
JLLWrappers.@declare_executable_product(esl_histplot)
JLLWrappers.@declare_executable_product(esl_mask)
JLLWrappers.@declare_executable_product(esl_reformat)
JLLWrappers.@declare_executable_product(esl_selectn)
JLLWrappers.@declare_executable_product(esl_seqrange)
JLLWrappers.@declare_executable_product(esl_seqstat)
JLLWrappers.@declare_executable_product(esl_sfetch)
JLLWrappers.@declare_executable_product(esl_shuffle)
JLLWrappers.@declare_executable_product(esl_ssdraw)
JLLWrappers.@declare_executable_product(esl_weight)
JLLWrappers.@declare_executable_product(hmmalign)
JLLWrappers.@declare_executable_product(hmmbuild)
JLLWrappers.@declare_executable_product(hmmconvert)
JLLWrappers.@declare_executable_product(hmmemit)
JLLWrappers.@declare_executable_product(hmmfetch)
JLLWrappers.@declare_executable_product(hmmlogo)
JLLWrappers.@declare_executable_product(hmmpgmd)
JLLWrappers.@declare_executable_product(hmmpress)
JLLWrappers.@declare_executable_product(hmmscan)
JLLWrappers.@declare_executable_product(hmmsearch)
JLLWrappers.@declare_executable_product(hmmsim)
JLLWrappers.@declare_executable_product(hmmstat)
JLLWrappers.@declare_executable_product(jackhmmer)
JLLWrappers.@declare_executable_product(makehmmerdb)
JLLWrappers.@declare_executable_product(nhmmer)
JLLWrappers.@declare_executable_product(nhmmscan)
JLLWrappers.@declare_executable_product(phmmer)
function __init__()
    JLLWrappers.@generate_init_header(GSL_jll)
    JLLWrappers.@init_executable_product(
        alimask,
        "bin/alimask",
    )

    JLLWrappers.@init_executable_product(
        esl_afetch,
        "bin/esl-afetch",
    )

    JLLWrappers.@init_executable_product(
        esl_alimanip,
        "bin/esl-alimanip",
    )

    JLLWrappers.@init_executable_product(
        esl_alimap,
        "bin/esl-alimap",
    )

    JLLWrappers.@init_executable_product(
        esl_alimask,
        "bin/esl-alimask",
    )

    JLLWrappers.@init_executable_product(
        esl_alimerge,
        "bin/esl-alimerge",
    )

    JLLWrappers.@init_executable_product(
        esl_alipid,
        "bin/esl-alipid",
    )

    JLLWrappers.@init_executable_product(
        esl_alistat,
        "bin/esl-alistat",
    )

    JLLWrappers.@init_executable_product(
        esl_compalign,
        "bin/esl-compalign",
    )

    JLLWrappers.@init_executable_product(
        esl_compstruct,
        "bin/esl-compstruct",
    )

    JLLWrappers.@init_executable_product(
        esl_construct,
        "bin/esl-construct",
    )

    JLLWrappers.@init_executable_product(
        esl_histplot,
        "bin/esl-histplot",
    )

    JLLWrappers.@init_executable_product(
        esl_mask,
        "bin/esl-mask",
    )

    JLLWrappers.@init_executable_product(
        esl_reformat,
        "bin/esl-reformat",
    )

    JLLWrappers.@init_executable_product(
        esl_selectn,
        "bin/esl-selectn",
    )

    JLLWrappers.@init_executable_product(
        esl_seqrange,
        "bin/esl-seqrange",
    )

    JLLWrappers.@init_executable_product(
        esl_seqstat,
        "bin/esl-seqstat",
    )

    JLLWrappers.@init_executable_product(
        esl_sfetch,
        "bin/esl-sfetch",
    )

    JLLWrappers.@init_executable_product(
        esl_shuffle,
        "bin/esl-shuffle",
    )

    JLLWrappers.@init_executable_product(
        esl_ssdraw,
        "bin/esl-ssdraw",
    )

    JLLWrappers.@init_executable_product(
        esl_weight,
        "bin/esl-weight",
    )

    JLLWrappers.@init_executable_product(
        hmmalign,
        "bin/hmmalign",
    )

    JLLWrappers.@init_executable_product(
        hmmbuild,
        "bin/hmmbuild",
    )

    JLLWrappers.@init_executable_product(
        hmmconvert,
        "bin/hmmconvert",
    )

    JLLWrappers.@init_executable_product(
        hmmemit,
        "bin/hmmemit",
    )

    JLLWrappers.@init_executable_product(
        hmmfetch,
        "bin/hmmfetch",
    )

    JLLWrappers.@init_executable_product(
        hmmlogo,
        "bin/hmmlogo",
    )

    JLLWrappers.@init_executable_product(
        hmmpgmd,
        "bin/hmmpgmd",
    )

    JLLWrappers.@init_executable_product(
        hmmpress,
        "bin/hmmpress",
    )

    JLLWrappers.@init_executable_product(
        hmmscan,
        "bin/hmmscan",
    )

    JLLWrappers.@init_executable_product(
        hmmsearch,
        "bin/hmmsearch",
    )

    JLLWrappers.@init_executable_product(
        hmmsim,
        "bin/hmmsim",
    )

    JLLWrappers.@init_executable_product(
        hmmstat,
        "bin/hmmstat",
    )

    JLLWrappers.@init_executable_product(
        jackhmmer,
        "bin/jackhmmer",
    )

    JLLWrappers.@init_executable_product(
        makehmmerdb,
        "bin/makehmmerdb",
    )

    JLLWrappers.@init_executable_product(
        nhmmer,
        "bin/nhmmer",
    )

    JLLWrappers.@init_executable_product(
        nhmmscan,
        "bin/nhmmscan",
    )

    JLLWrappers.@init_executable_product(
        phmmer,
        "bin/phmmer",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
